version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: 'widen'
    schedule:
      interval: 'daily'
    ignore:
      # Ignore all major updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
