name: Tests and Checks

on: [pull_request]

env:
  REACT_APP_CHAIN_ID: 97
  FAST_REFRESH: false

jobs:
  typecheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install deps
        run: yarn

      - name: TSC
        run: yarn run typecheck

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install deps
        run: yarn

      - name: Lint
        run: yarn lint

      - name: pretty
        run: yarn pretty

      - name: Lint styles
        run: yarn lint-styles

  storybooks:
    runs-on: self-hosted
    container:
      image: node:14.15.1-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow

      - run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
          sh -c 'echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          apt-get update -y
          apt-get install google-chrome-stable -y

      - name: Install deps
        run: yarn

      - name: Build static storybooks
        run: yarn build-storybook

      - name: Snapshot
        run: yarn loki --chromeFlags="--headless --no-sandbox --disable-dev-shm-usage"

      - name: Reg-suit
        run: yarn regression

      - name: Deploy
        if: github.ref == 'refs/heads/develop'
        run: yarn deploy-storybook --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install deps
        run: yarn

      - name: Run tests
        run: yarn test
