name: Tests and Checks

on: [push]

env:
  VITE_ENVIRONMENT: 'ci'
  NODE_OPTIONS: '--max_old_space_size=4096'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'
          cache: 'yarn'

      - name: Install deps
        run: yarn

      - name: Typecheck
        run: yarn typecheck

      - name: Pretty
        run: yarn lint:format

      - name: Lint styles
        run: yarn lint:styles

      - name: Lint
        run: yarn lint:ts

  test:
    runs-on: ubuntu-20.04
    container:
      image: node:14.15.1-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'
          cache: 'yarn'

      - name: Install deps
        run: yarn

      - name: Run tests and collect coverage
        run: yarn test --coverage

      - name: 'Report Coverage'
        if: always() # Also generate the report even if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
